- chronicle/src/main/java/net/openhft/chronicle/RemoteChronicleQueue.java
- chronicle/src/test/java/net/openhft/chronicle/tcp/StatefulIndexedChronicleTest.java
- chronicle/src/test/java/net/openhft/chronicle/tcp/StatefulVanillaChronicleTest.java
- chronicle/src/test/java/net/openhft/chronicle/tcp/StatelessIndexedChronicleTest.java
- chronicle/src/test/java/net/openhft/chronicle/tcp/StatelessVanillaChronicleTailerTest.java
> CHRON-103 - Chronicle-Queue Subscriber stop working after Publisher restarted

- chronicle/src/main/java/net/openhft/chronicle/IndexedChronicle.java
- chronicle/src/test/java/net/openhft/chronicle/IndexedChronicleLargeFileTest.java
Fix indexForRead with IndexedChronicle test case for large file
> Fix indexForRead with IndexedChronicle test case for large file

- README.md
> Fixed syste. typos

- chronicle/pom.xml
- chronicle/src/main/java/net/openhft/chronicle/VanillaIndexCache.java
- chronicle/src/test/java/net/openhft/chronicle/VanillaBlockSizeTest.java
- chronicle/src/test/java/net/openhft/chronicle/VanillaChronicleTest.java
- chronicle/src/test/java/net/openhft/chronicle/VanillaChronicleTestBase.java
- chronicle/src/test/java/net/openhft/chronicle/VanillaLatencyTest.java
CHRON-114 VanillaChronicle AssertionError (#153)
> CHRON-114 - VanillaChronicle AssertionError (#153) 

- chronicle/pom.xml
- chronicle/src/main/java/net/openhft/chronicle/RemoteChronicleQueue.java
- chronicle/src/main/java/net/openhft/chronicle/tools/WrappedExcerpt.java
- chronicle/src/main/java/net/openhft/chronicle/tools/WrappedExcerptAppender.java
- chronicle/src/main/java/net/openhft/chronicle/tools/WrappedExcerptAppenders.java
- chronicle/src/main/java/net/openhft/chronicle/tools/WrappedExcerptTailer.java
* Bug in net.openhft.chronicle.RemoteChronicleQueue
* Update poms
> CHRON-118 - Bug in net.openhft.chronicle.RemoteChronicleQueue

- README.md
I found a few typos while reading your documentation and tried to correct them. I am not a native English speaker, so I hope I didn't make any wrong textual corrections.
> Textual adjustments

- chronicle-queue/README.md
Added Question Answers into readme.md
> QUEUE-23 add the following information to the chronicle queue readme.md

- chronicle-queue/src/test/java/net/openhft/chronicle/queue/ChronicleQueueLatencyDistribution.java
- chronicle-queue/src/test/java/net/openhft/chronicle/queue/ChronicleQueueTestBase.java
@danielshaya can you review the correctness of my PR and merge it if OK ?
> Add affinity and warmup to ChronicleQueueLatencyDistribution test

- pom.xml
- src/main/java/net/openhft/chronicle/queue/Excerpt.java
- src/main/java/net/openhft/chronicle/queue/ExcerptAppender.java
- src/main/java/net/openhft/chronicle/queue/ExcerptTailer.java
- src/main/java/net/openhft/chronicle/queue/impl/Excerpts.java
- src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java
- src/test/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueTest.java
woo checked into he wrong branch
> Lburgazzoli excerpt factory

- src/test/java/net/openhft/chronicle/queue/impl/single/ToEndTest.java
Not sure if this is correct behavior. Close if this is completely wrong.
> Reference count continually increases when calling toEnd on a Tailer

- src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueExcerpts.java
- src/test/java/net/openhft/chronicle/queue/impl/single/ToEndTest.java
approximateLastIndex was acquiring the store for lastCycle, but not updating this.cycle.
> Improved test and fixed #281

- src/test/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueTest.java
When writing some text in addition the index, the test throws an AssertionError.
Caused by: java.lang.AssertionError: ~~~~~~~~~~~~~~ thread: ForkJoinPool.commonPool-worker-3  **pos1: 2418297 seq1: 9236 seq2: 9237**
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender.**checkWritePositionHeaderNumber(SingleChronicleQueueExcerpts.java:331)**
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreAppender$StoreAppenderContext.close(SingleChronicleQueueExcerpts.java:676)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.writeTestDocument(SingleChronicleQueueTest.java:2113)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.doSomthing(SingleChronicleQueueTest.java:2094)
at …
> SingleChronicleQueueExceprts$StoreAppender.checkWritePositionHeaderNumber throws  AssertionError

- src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueStore.java
- src/test/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueTest.java
This very well may be architecture dependent as I have only witnessed on Skylake.
> writePosition cache alignment

- src/test/java/net/openhft/chronicle/queue/ChronicleQueueMethodsWithoutParameters.java
Test that shows problems with invocation of method without parameters.
I hope this help in issue fixing :)
> Test shows problems with invocation of method without parameters.

- src/test/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueTest.java
I created a test to reproduce an issue with being unable to read from
the end of the queue if all of the following conditions are met:
1) The time is at least one cycle in the future compared to the time the
last update was written to the chronicle instance
2) We read FORWARD at least once after reaching end of the queue before
trying to read BACKWARD. In this test, queue has only one element, so we
are trying to read from it two times.
If both of this conditions are met, all further attempts to read
backward from the end of the queue are failing.
If any of the conditions are not met (e.g. time is not set to the future cycle), the issue does not reproduce.
(just in case, I am running this on Windows 7 and JDK 8 u101)
> Tailer test to show issue with backward reading cycles written long ago

- src/test/java/net/openhft/chronicle/queue/TailerDirectionTest.java
> Unit test for checking Tailer reading after switching read direction

- src/main/java/net/openhft/chronicle/queue/TailerState.java
- src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueExcerpts.java
Subject says it all. I'm not a native speaker, but I've never come across the word "behond".
> Fix typo: BEHOND_START_OF_CYCLE -> BEYOND_START_OF_CYCLE

- src/test/java/net/openhft/chronicle/queue/TailerDirectionTest.java
I have the use case of "read the last 1000 messages in a queue", but the tailer doesn't switch cycles back. Should this be possible in Chronicle Queue?
I tried switch cycles backwards manually with tailer.moveToIndex(tailer.index() -1) but I seem to land in nowhere land.
(Test fails against 4.5.21)
> Tailer can't switch cycles reading backwards

- src/test/java/net/openhft/chronicle/queue/LastIndexAppendedTest.java
I was expecting that the second appender would just add entries, but it rewrote them. Anything I am missing?
> Failing Test with successive appenders.

- README.adoc
- src/test/java/net/openhft/chronicle/queue/OvertakeTest.java
Things leftover from yesterday. May be useful.
> Cleanup and additional multithread test

- chronicle-sandbox/src/main/java/net/openhft/chronicle/queue/impl/ringbuffer/BytesRingBuffer.java
- src/main/java/net/openhft/chronicle/queue/impl/AbstractChronicleQueueBuilder.java
- src/main/java/net/openhft/chronicle/queue/impl/WireStoreSupplier.java
- src/main/java/net/openhft/chronicle/queue/impl/single/SCQIndexing.java
- src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java
- src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueExcerpts.java
I found some Javadoc typos and fixed them
> Fix a few Javadoc typos

- docs/FAQ.adoc
Questions from http://stackoverflow.com/questions/38415008/java-chronicle-throwing-illegalstateexecption-at-high-number-of-messages and http://stackoverflow.com/questions/41429878/chronicle-queue-events-listener
> 2 questions added to the end

- docs/FAQ.adoc
> Typos in FAQ

- README.adoc
> readme correction

- src/main/java/net/openhft/chronicle/IndexedChronicle.java
IndexedChronicle now uses the aligned operations added to Java-Lang
> IndexedChronicle now uses the aligned operations added to Java-Lang

- src/main/java/net/openhft/chronicle/queue/reader/ChronicleHistoryReader.java
- src/test/java/net/openhft/chronicle/queue/impl/single/PretoucherTest.java
- src/test/java/net/openhft/chronicle/queue/reader/ChronicleReaderTest.java
Close resources with try-with-resources block to prevent resource leaks.
> Resource leaks

- src/main/java/net/openhft/chronicle/queue/service/ServiceWrapperBuilder.java
- src/test/java/net/openhft/chronicle/queue/bench/ThroughputPerfMain2.java
Suppress decrecation warnings for APIs that have no replacements.
> Polish: suppress deprecation warnings

- src/test/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueTest.java
Replace deprecated createAppender with acquireAppender.
> Polish: replace deprecated createAppender() with acquireAppender()

- src/main/java/net/openhft/chronicle/queue/BenchmarkMain.java
> Polish: remove dead code

- src/main/java/net/openhft/chronicle/queue/ChronicleQueue.java
Suppress varargs conversion warning.
> Polish: suppress varargs conversion warning

- src/test/java/net/openhft/chronicle/queue/SingleChroniclePerfMain.java
Replace deprecated createAppender with acquireAppender.
> Polish: replace deprecated createAppender with acquireAppender

- src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java
- src/test/java/net/openhft/chronicle/queue/QueueAppendAfterRollReplayedIssueTest.java
I assume the StoreAppenderContext should not be open by default
Closes #706
> Fix uninitialised writing context defaulting to open, closes #706

- .github/dependabot.yml
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
﻿
> enable Dependabot 2
