OpenHFT/Chronicle-Queue

chronicle/pom.xml
chronicle/src/test/java/net/openhft/chronicle/VanillaBlockSizeTest.java
chronicle/src/test/java/net/openhft/chronicle/VanillaLatencyTest.java

This is an infinite running test, but after 500,000,000 excerpts written I get the following error:
Exception in thread "main" java.lang.AssertionError
at net.openhft.chronicle.VanillaIndexCache.append(VanillaIndexCache.java:203)
at net.openhft.chronicle.VanillaChronicle$VanillaAppenderImpl.finish(VanillaChronicle.java:625)
at net.openhft.chronicle.VanillaBlockSizeTest.testMaxSize(VanillaBlockSizeTest.java:56)
at net.openhft.chronicle.VanillaBlockSizeTest.main(VanillaBlockSizeTest.java:68)
I only get this error when I set dataBlockSize and indexBlockSize.

Vanilla latency

---

src/test/java/net/openhft/chronicle/queue/impl/single/ToEndTest.java

tailer.toEnd() on a queue that has an appender that has not wrote causes the tailer to roll, and not receive any messages.

tailer.toEnd() before write

---

src/test/java/net/openhft/chronicle/queue/BackwardsRollIssue.java

Test fails most of the time, but still not always when running 2M messages through it.
A tailer moves back to the first index ever read, sometimes both tailers at once.

Added failing test for BackwardsRollIssue.

---

src/test/java/net/openhft/chronicle/queue/CycleNotFoundTest.java

Haven't been able to nail down exactly what is happening here but it's definitely related to TailerState.CYCLE_NOT_FOUND and causes the tailer to either stop altogether or not receive any messages from a cycle.
high level stack trace:
> java.lang.UnsupportedOperationException
> 	at net.openhft.chronicle.bytes.NoBytesStore.readByte(NoBytesStore.java:148)
> 	at net.openhft.chronicle.bytes.RandomDataInput.readUnsignedByte(RandomDataInput.java:86)
> 	at net.openhft.chronicle.bytes.AbstractBytes.uncheckedReadUnsignedByte(AbstractBytes.java:274)
> 	at net.openhft.chronicle.wire.BinaryWire.readCode(BinaryWire.java:1078)
> 	at net.openhft.chronicle.wire.BinaryWire$BinaryValueIn.int64(BinaryWire.java:2901)
> 	at net.openhft.chronicle.queue.CycleNotFoundTest.lambda$tailerCycleNotFoundTest$0(CycleNot …

Added test for CYCLE_NOT_FOUND causing missing messages.

---

src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueStore.java

Reads of SCQS.writePosition were causing 'WARN: add padding for concurrent appenders...' message. After padding the warning is gone.

SCQS.writePosition padding

---

pom.xml
src/main/java/net/openhft/chronicle/queue/impl/single/SCQIndexing.java
src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueExcerpts.java
src/test/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueTest.java

Some value reads were not consistently Volatile in accordance with other accessors. Please review.

Cc appender fixes

---

src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java
src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueExcerpts.java

This is another step in solving #306 : some store usages never call release, thus preventing the reference count from reaching zero and the resources from being freed.

fixed store reference leaks

---

src/test/java/net/openhft/chronicle/queue/ReadWriteTest.java

If I switch a queue to read-only, tailers can't go to the end anymore. I have difficulties understanding the read-only mode.

Failing read only test: tailer can't get toEnd()

---

src/test/java/net/openhft/chronicle/queue/TailerDirectionTest.java
src/test/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueTest.java

Fails with:
```
java.lang.NullPointerException
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.inACycle(SingleChronicleQueueExcerpts.java:988)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.next(SingleChronicleQueueExcerpts.java:878)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueExcerpts$StoreTailer.readingDocument(SingleChronicleQueueExcerpts.java:856)
at net.openhft.chronicle.queue.ExcerptTailer.readingDocument(ExcerptTailer.java:41)
at net.openhft.chronicle.queue.impl.single.SingleChronicleQueueTest.testNegativeEPOC(SingleChronicleQueueTest.java:1117)
```

Failing Test for Negative Epoch

---

src/test/java/net/openhft/chronicle/queue/OvertakeTest.java

Double close on DocumentContext moves the index by 2, not 1. Result: Appenders and Tailers disagree on the index position.
Please fix this. It cost me so much time to isolate.

Failing test with runaway index.

---

src/test/java/net/openhft/chronicle/queue/FsFullReadTest.java
src/test/java/net/openhft/chronicle/queue/FsFullWriteTest.java

Test for a damaged CQ file. It would be great if CQ could extract more
entries from such a "damaged" file and fail more gracefully.

"Damaged" CQ file.

---

src/main/java/net/openhft/chronicle/queue/impl/WireStorePool.java
src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java
src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueExcerpts.java
src/test/java/net/openhft/chronicle/queue/impl/single/ToEndTest.java

To find leaks I run some simple scenario and then check open file descriptors using linux "lsof" command. At first I suspected that leaks were caused by the direct call "store.release()". But the actual problem is "reserve" after "acquire".

Fix resource leaks caused by WireStore refCounting errors

---

src/test/java/net/openhft/chronicle/queue/impl/single/TooManyOpenFilesTest.java

That is one more form of resource leaks. Closers are stored in WeakHashMap, and so from time to time gc() just eats them. In my application I need constant set of trailers and appenders, so I just replaced WeakHashMap with HashMap. In general case it makes sense to apply some finalisation approach, e.g.  phantom references.

Test for too many files problem

---

src/main/java/net/openhft/chronicle/queue/ChronicleReaderMain.java
src/main/java/net/openhft/chronicle/queue/reader/ChronicleReader.java
src/main/java/net/openhft/chronicle/queue/reader/ChronicleReaderPlugin.java

The default behaviour of ChronicleReader is to render the queue assuming it has been written using the yaml text format.  This doesn't work when the queue was written using a binary format.  In this case we need to be able to add a custom handler which is possible with this patch.
It is full backward compatible.

Added custom queue handling.

---

src/main/java/net/openhft/chronicle/queue/impl/single/StoreComponentReferenceHandler.java

Similar to https://github.com/OpenHFT/Chronicle-Core/pull/69 but for Chronicle-Queue
Between these two PRs, I've observed with a profiler that all threads are being cleaned up after these shutdown hooks are run.

Add shutdown hook to stop thread local cleaner executor service

---

src/test/java/net/openhft/chronicle/queue/LastAppendedTest.java

For proxy to access it, message must be public:
mvn clean test -Dtest=net.openhft.chronicle.queue.LastAppndedTest
results in passing tests but this is printed to error stream:
```
/net/openhft/chronicle/wire/proxy/Proxy4.java:8: error: net.openhft.chronicle.queue.LastAppendedTest.Msg is not public in net.openhft.chronicle.queue.LastAppendedTest; cannot be accessed from outside package
public class Proxy4 implements net.openhft.chronicle.queue.LastAppendedTest.Msg,
^
[main] DEBUG net.openhft.chronicle.wire.VanillaMethodWriterBuilder - 
java.lang.ClassNotFoundException: net.openhft.chronicle.wire.proxy.Proxy4
package net.openhft.chronicle.wire.proxy;
import net.openhft.chronicle.core.Jvm;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import …
```

Bug - proxy needs public access

---

src/test/java/net/openhft/chronicle/queue/impl/single/MessageHistoryTest.java
src/test/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueTest.java
src/test/java/net/openhft/chronicle/queue/impl/single/preroucher/PretoucherSoakTest.java

Replace deprecated build() method with get().

Polish: replace deprecated build() method with get()

---

src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueExcerpts.java
src/test/java/net/openhft/chronicle/queue/bench/ThroughputPerfMain.java
src/test/java/net/openhft/chronicle/queue/bench/ThroughputPerfMain2.java

Suppress the restricted API warnings from `UnsafeMemory.UNSAFE`:
```
Access restriction: The method 'Unsafe.copyMemory(long, long, long)' is not API
(restriction on required library '/home/jan/jdk1.8.0_202/jre/lib/rt.jar')
ThroughputPerfMain.java line 1
Access restriction: The method 'Unsafe.copyMemory(long, long, long)' is not API
(restriction on required library '/home/jan/jdk1.8.0_202/jre/lib/rt.jar')
ThroughputPerfMain2.java line 79
Access restriction: The method 'Unsafe.getIntVolatile(Object, long)' is not API
(restriction on required library '/home/jan/jdk1.8.0_202/jre/lib/rt.jar')
SingleChronicleQueueExcerpts.java line 1059
Access restriction: The method 'Unsafe.putOrderedInt(Object, long, int)' is not API
(restriction on required library '/home/jan/jdk1.8.0_202/jre/lib/rt.jar') …
```

Polish: suppress restricted API warnings from use of Unsafe

---

src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java

```
Type safety: The method accept(Object) belongs to the raw type Consumer. References to generic type Consumer<T> should be parameterized	SingleChronicleQueue.java line 601
```

Polish:  suppress warning unparameterized raw type Consumer<T>

---

src/test/java/net/openhft/chronicle/queue/DtoBytesMarshallableTest.java

```
Type safety: The method readUtf8(Appendable) belongs to the raw type StreamingDataInput. References to generic type StreamingDataInput<S> should be parameterized
```

Polish: suppress warning on unparameterized readUtf8

---

src/test/java/net/openhft/chronicle/queue/bench/QueueSingleThreadedJLBHBenchmark.java

```
Type safety: The method bytesStore(BytesStore, long, long) belongs to the raw type Byteable. References to generic type Byteable<B,Underlying> should be parameterized
```

Polish: suppress type safety warning on unparameterized Byteable

---

src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleMultiThreadTest.java

```
Type safety: The expression of type RollCycleMultiThreadTest.ParallelQueueObserver needs unchecked conversion to conform to Callable<Object>
```

Polish: suppress warning on unchecked conversion

---

src/main/java/net/openhft/chronicle/queue/ChronicleHistoryReaderMain.java
src/main/java/net/openhft/chronicle/queue/ChronicleReaderMain.java

Very minor but maybe it would be a bit nicer to have something more descriptive than just usage printed when no arguments are provided. It seems to be a de facto standard to do so if a tool doesn't have lots of options and huge help info. E.g., off the top of my head, CLI such as java, groovy, sdkman do this. Code is based on http://commons.apache.org/proper/commons-cli/usage.html

Make help printed by default (no args) for CLI tools
